name: Update data
on:
  schedule:
    - cron: '0 0-23 * * *'
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: run script
        run: |
          echo ::set-output name=results::$(python update/update.py)
        id: run_script
      - name: what changed
        env:
          RESULTS: ${{ steps.run_script.outputs.results }}
        run: |
          echo ::set-output name=number::$(echo "$RESULTS" | jq ".number")
          echo ::set-output name=message::$(echo "$RESULTS" | jq ".message" | sed -e "s/\"//g")
        id: changed
      - name: log
        env:
          NUMBER: ${{ steps.changed.outputs.number }}
          MESSAGE: ${{ steps.changed.outputs.message }}
        run: |
          echo "results"
          echo "$NUMBER changes"
          echo "message: $MESSAGE"
      - name: commit
        env:
          NUMBER: ${{ steps.changed.outputs.number }}
          MESSAGE: ${{ steps.changed.outputs.message }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.changed.outputs.number > 0
        run: |
          git config --global user.email "covid19-bot@example.com"
          git config --global user.name "covid19-bot"
          git add -A
          git status
          git commit -m "[ci] $MESSAGE"
          git push -q "https://$GH_TOKEN@github.com/pr0nstar/covid19-bolivia.git" master
  update-opsoms:
    name: update opsoms data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@opsoms
        with:
          ref: opsoms
          lfs: true
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: install python and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: run opsomos update script
        id: run_update_script
        run: |
          python update/update_opsoms.py
      - name: git status
        id: git-status
        run: |
          git config --global user.email "covid19-bot@example.com"
          git config --global user.name "covid19-bot"
          echo ::set-output name=result::$(git status | tr -d "\n" | grep -c "nothing to commit")
      - name: commit
        if: steps.git-status.outputs.result == 0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add -A
          git commit -m "[ci] actualización"
          git push -q "https://$GH_TOKEN@github.com/pr0nstar/covid19-bolivia.git" main
©
